# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
      include:
        - refs/tags/{tagname}

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Linux_Build
    displayName: Linux Job
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build Linux Docker Image
      inputs:
        command: build
        dockerfile: '**/linux.dockerfile'
        tags: |
          $(tag)
          latest
  - job: Windows_Build
    displayName: Windows Job
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: Docker@2
      displayName: Build Windows Docker Image
      inputs:
        command: build
        dockerfile: '**/windows.dockerfile'
        tags: |
          $(tag)-win
          latest-win
