# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  tags:
    include:
    - v*

resources:
- repo: self

variables:
  tag: '$(Build.SourceBranchName)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Linux_Build
    displayName: Linux Job
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build Linux Docker Image
      inputs:
        command: build
        dockerfile: '**/linux.dockerfile'
        tags: |
          $(tag)
          latest
  - job: Windows_1809_Build
    displayName: Windows 1809 Job
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: Docker@2
      displayName: Build Windows 1809 Docker Image
      inputs:
        command: build
        dockerfile: '**/windows-1809.dockerfile'
        tags: |
          $(tag)-win1809
          latest-win1809
